Require gum
Require glow

Set Theme { "name": "Whimsy", "black": "#535178", "yellow": "#EFD55B", "blue": "#443462", "cyan": "#ABE2D6", "red": "#F08FC3", "purple": "#443462", "white": "#F2E1A6", "brightBlack": "#535178", "brightYellow": "#fdd877", "brightBlue": "#65aef7", "brightPurple": "#aa7ff0", "brightWhite": "#F2E1A6", "background": "#6F336E", "foreground": "#F3D960", "selectionBackground": "#6C347B", "cursorAccent": "#EF8EC5", "cursor": "#B563A8" }
Set WindowBar Colorful

Require clear
Require echo

Set Shell "bash"

Set Width 1200
Set Height 600
Set CursorBlink true

Set FontSize 34
Set Margin 35
Set MarginFill "components/margin-fill.png"
Set BorderRadius 10
Set Framerate 30

Type "Hello! 🙌 " Sleep 3s Backspace 9 Sleep 2s
Type "echo Welcome to Soroban Quest..." Sleep 3s Backspace 16 Sleep 2s
Type "Stellar Quest 3!!! 👋 🚀 👩‍💻" Sleep 3s Enter Sleep 1s
Copy "echo Welcome to Stellar Quest 3!!! 👋 🚀 👩‍💻"
Paste Sleep 750ms Enter
Paste Sleep 500ms Enter
Paste Sleep 400ms Enter
Paste Sleep 300ms Enter
Paste Sleep 200ms Enter

Sleep 2s
Hide
Type@10ms `clear` Enter
Sleep 2s
Show

Type "echo ...sorry... got carried away... && clear" Sleep 3s Enter

Type "...Let's load up the training 🔥 program! 💪 ✨" Sleep 3s

Sleep 2s
Hide
Type@10ms `clear` Enter
Sleep 2s
Show

Output intro-0-0.mp4