name: Welcome new Quester

on:
  workflow_dispatch:
  fork:
    types: [ created ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: |
            
            const discussionNumber = 3;
            console.log("Discussion Number:", discussionNumber);
            
              await github.rest.discussions.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              discussion_number: discussionNumber,
              body: "Welcome ${{github.actor}} to the Stellar Quest 3 !!!!"
            });
